version: '3.8'
services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        - username=${USERNAME:-vscode}
        - useruid=${USERUID:-1000}
        - usergid=${USERGID:-1000}
    volumes:
      - ..:/workspace:cached
      - gohome:/home/${USERNAME:-vscode}
    command: /bin/sh -c "while sleep 1000; do :; done"
    user: vscode
volumes:
  gohome:
